compile:
	mvn compile
	mvn exec:java -Dexec.mainClass=Main -e
clean:
	mvn clean
	find . -type f -iname \*.jpg -delete
	# rm -f resources/trainingSet/barend/grayScaleImages/*.jpg
	# rm -f resources/trainingSet/barend/lbpImages/*.jpg
